### ISSUE TITLE
Example code images do not include styles

### ISSUE THREAD

**Issue by tdreid** [fullstackreact/30-days-of-react#2]
* it's not clear what stylesheet(s) are applied to the examples
* the examples use classes from font awesome, but the link to font awesome isn't mentioned or shown

So that if the reader is following along our days 1 through 4 looks like this...
![image](https://cloud.githubusercontent.com/assets/868675/22982126/2d531e64-f36c-11e6-9719-01506bb0d860.png)

And yours looks like...
![image](https://cloud.githubusercontent.com/assets/868675/22982151/419acda4-f36c-11e6-835a-7198ade817d1.png)

This could lead to the reader believing they've made a mistake in React when it's really more a matter of style.

**Comment by heyalistair** [comment]
I also ran into similar issues, which is frustrating because the tutorials do such a good job of getting you set up to run the code yourself, at first. 

I know we only get to styles in day 9 (and even then we don't have access to the stylesheet the examples use), but it could be as easy as including some milestone test code samples, after every week 5-7 days, so that we can look at this and see where we are at.

**Comment by ThetaMinotaur** [comment]
I'm on lesson 07 and I included the 4.7.0 fontawesome stylesheet but the "fa-more" class doesn't seem to exist unless it's in an older version.

**Comment by ethanx94** [comment]
Real deal breaker, I don't want to buy the book if I can't even work through the freebie. I thought this would be the pinnacle of React, seeing as how it touted all other tutorials as "incomplete and confusing."

**Comment by auser** [comment]
Alright, I updated the repo to include all the demos _directly_ from the blog. Does this help solve this for ya'll?

**Comment by tdreid** [comment]
Sounds useful. Thanks, @auser !
