### ISSUE TITLE
build error - Error: Cannot find module '/home/trung/30-days-of-react/scripts/cqmd.js'

### ISSUE THREAD

**Issue by mickeyjohn** [fullstackreact/30-days-of-react#5]
Hi, 
I got this error "Error: Cannot find module '/home/trung/30-days-of-react/scripts/cqmd.js'" while building the project. Then the app still runs at localhost:3000 but no styles loaded. Please help.

**Comment by mickeyjohn** [comment]
![screenshot from 2017-04-11 12 39 09](https://cloud.githubusercontent.com/assets/14140486/24923830/cc7c0ba2-1ec0-11e7-94e5-d821a4f483a6.png)

[2017-04-11T18_04_12_721Z-debug.log.txt](https://github.com/fullstackreact/30-days-of-react/files/914280/2017-04-11T18_04_12_721Z-debug.log.txt)

**Comment by ctrimm** [comment]
For what it's worth @auser, I'm also seeing this issue when fetching day-8, installing the dependencies via yarn, and running via yarn.

**Comment by MichaelMallett** [comment]
I actually haven't managed to get a single day to build because I get this error. I do get an error when running yarn install, something about fsevents not being installed

ERR! Tried to download(404): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.0.17/fse-v1.0.17-node-v57-darwin-x64.tar.gz \nnode-pre-gyp ERR! Pre-built binaries not found for fsevents@1.0.17 and node@8.6.0


Ran using npm install instead of yarn and still couldn't get yarn run build to work. Downgraded node to version 6 as that seemed to be pointed out by googling fsevents error. No longer get a problem installing fsevents, but still get the same cqmd.js error.

I can't seem to access this app at all, I just get a page with no styling and the text from the article.

**Comment by MichaelMallett** [comment]
@mickeyjohn Any reason why you've closed this issue without comment?
